### ISSUE TITLE
Search results contain more details

### ISSUE THREAD

**Issue by mtorres253** [18F/hub#523]
So that 18F employees can find the information they need, the existing search should return important details for each match that will give users a way to choose the best result.

Acceptance Criteria:
Work with existing lunr.js search to see how many of these items we can get returned in the search results. Demo could just be doing  search and seeing the results in console.

Suggested data in search results:
Corpus (where the content lives)
Title
Content snippet
URL to content
Guides, Handbook or some other source

**Comment by mbland** [comment]
Totally against this. Part of the reason the Hub search is "unusable" (which is surely a bit of an exaggeration) is because I never got around to applying the `skip_index` filter that I implemented in `jekyll_pages_api_search` to keep things like snippets out of the search results. Also never got around to adding `tags` front matter that could also help weight things. Adding Elasticsearch would violate the principle of keeping the system very light and lean.

**Comment by mbland** [comment]
Another aspect: we've been gutting The Hub's content and cultivating it in the Handbook. I expect porting it back will materially improve the existing search as well.

Basically, let's fix all  the things we can first, then evaluate the search quality and whether a switch is warranted.

**Comment by melodykramer** [comment]
I noticed above that you said tags would improve search functionality. I haven't been including these in the frontmatter but am happy to add them - is that something I should prioritize?

**Comment by mbland** [comment]
Sure! We can also play with the weights of the various components in `_config.yml`, per https://github.com/18F/jekyll_pages_api_search/#installation:

```yaml
# Configuration for jekyll_pages_api_search plugin gem.
jekyll_pages_api_search:
  # Uncomment this to speed up site generation while developing.
  #skip_index: true

  # Each member of `index_fields` should correspond to a field generated by
  # the jekyll_pages_api. It can hold an optional `boost` member as a signal
  # to Lunr.js to weight the field more highly (default is 1).
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body:
```
